name: yt_downloader
description: "A new Flutter project."
publish_to: "none"
version: 0.1.3

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  window_manager: ^0.4.3
  youtube_explode_dart: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
